#!/bin/bash

set -eu -o pipefail # fail on error and report it, debug all lines

sudo -n true
test $? -eq 0 || exit 1 "you should have sudo privilege to run this script"

echo installing packages

sudo apt update -y
while read -r p ; do apt-get install -y $p ; done < <(cat << "EOF"
    git
    python3-pip
    nodejs
    npm
EOF
)

while read -r p ; do pip install -y $p ; done < <(cat << "EOF"
    RPi.GPIO
    spidev
    pyserial
EOF
)

echo installing packages
echo you have 5 seconds to proceed ...
echo or
echo hit Ctrl+C to quit
echo -e "\n"
sleep 6

sudo apt-get install -y tig
